CU-4nmd9f_Subpages-Development_Sasha
minimal-dev/huebius_crypto pull request #1
Opened 2020-11-04 13:51 UTC by animetalist

2020-11-04 13:51 UTC, animetalist commented
Task linked: [CU-4nmd9f Subpages Development](https://app.clickup.com/t/4nmd9f)

2020-11-05 13:56 UTC, salexpro commented on src/js/components/_carousel.js
> +// // Wrap everything in an IIFE
убрать

2020-11-05 14:01 UTC, salexpro commented on src/pug/sections/_token.pug
> +    a.btn.btn-outline-primary.wide.token_btn(href='/token/')
на саму кнопку лучше ничего не вешай, их может легко стать 2 в том месте, оберни в див с классом `.token_btn` ну или что то по типу `.token_buttons`

2020-11-05 14:05 UTC, salexpro commented on src/scss/components/_base.scss
> +.hero--page {
почему сюда? почему не в `_hero.scss`

2020-11-05 14:06 UTC, salexpro requested changes
поменять названия картинок + комменты к файлам

2020-11-05 14:07 UTC, salexpro commented on src/js/components/_carousel.js
> +// })(jQuery, ResponsiveBootstrapToolkit);
убрать

2020-11-05 15:03 UTC, salexpro approved these changes

2020-11-05 15:03 UTC, merged